# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'CosyncJWTiOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CosyncJWTiOS
  pod 'RealmSwift', '=10.1.4'
  pod 'CryptoSwift'

end
